# Generated by Django 5.2.7 on 2025-11-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='usersnames',
        ),
    ]
