# Generated by Django 5.2.7 on 2025-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_rename_username_profile_usersnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usersnames',
            new_name='manager',
        ),
    ]
